import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import NavBar from "@/components/NavBar";
import Banner from "@/components/Banner";
import Specialties from "@/components/Specialties";
import About from "@/components/About";
import Statements from "@/components/Statements";
import styled from "styled-components";
import Contact from "@/components/Contact";

export default function Home() {
  return (
    <>
      <Head>
        <title>Ney Simões</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/favicon.ico" />
        <link rel="apple-touch-icon" sizes="57x57" href="/apple-icon-57x57.png"/>
      </Head>
      <Main>
        <NavBar />
        <Banner />
        <Specialties />
        <About />
        <Statements />
        <Contact />
      </Main>
      <footer className={styles.footer}></footer>
    </>
  );
}

const Main = styled.main`
  display: flex;
  justify-content: center;
  flex-direction: column;
  align-items: center;
  font-family: Poppins, sans-serif;
  font-size: 1.1rem;
  font-weight: 300;
`;
